### ISSUE TITLE
SPF domain is required but missing!

### ISSUE THREAD

**Issue by t2d** [bigio/spamassassin-dmarc#7]
Thank you for providing this plugin. However, it causes an error line in my journal, which I don't understand and can't find any info about:
```
SPF domain is required but missing!
```
Without this plugin SPF checks don't throw any error.

**Comment by bigio** [comment]
Which version of SpamAssassin are you running ?
The warning is printed on every mail message or once in a while ?

**Comment by t2d** [comment]
Thanks for your help. I just installed the Debian 11 package.
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye

$ spamassassin --version
SpamAssassin version 3.4.6
  running on Perl version 5.32.1

$ dpkg -l "libmail*perl" | grep ii
ii  libmail-authenticationresults-perl 2.20210112-1 all          object oriented Authentication-Results headers
ii  libmail-dkim-perl                  1.20200907-1 all          module to cryptographically identify the sender of email
ii  libmail-spf-perl                   2.9.0-5      all          Perl implementation of Sender Policy Framework and Sender ID
ii  libmailtools-perl                  2.21-1       all          modules to manipulate email in perl programs
```
The message comes for every mail.

**Comment by bigio** [comment]
You should also have Mail::DMARC and latest commit for this to work.

**Comment by t2d** [comment]
Awesome! I installed it like https://github.com/systemli/ansible-role-spamassassin/blob/master/tasks/dmarc.yml and the error messages are gone. Thank you!
