### ISSUE TITLE
Use of uninitialized value $domain in concatenation (.) or string

### ISSUE THREAD

**Issue by RvdHout** [bigio/spamassassin-dmarc#8]
Trying to install this plugin on SpamAssassin 3.4.4 ([Jam version, Windows](https://www.jam-software.com/spamassassin))

Installed Mail::DMARC::PurePerl using CPAN as i at first got warn: check_dmarc not supported, required module Mail::DMARC::PurePerl missing, after fixing this is see lines like these in my spamassassin log file:

`warn: Use of uninitialized value $domain in concatenation (.) or string at \etc\spamassassin\Dmarc.pm line 261.`  (Repeated 5 times for every mail that is being processed)

[line 261](https://github.com/bigio/spamassassin-dmarc/blob/master/Dmarc.pm#L261)

Anything i missed in my install, or something else is wrong?
SpamAssassin 3.4.4 is supported?

**Comment by bigio** [comment]
Atm the code is tested only on 3.4.6 and trunk but it should work on 3.4.4 as well.
I fixed error handling and with updated code you should have a better error message to understand the underlying issue.

**Comment by RvdHout** [comment]
Thx, i already fixed it myself by assigning a value to $domain, i will check out your new commit and replace my edited file

FYI, seems to run fine on 3.4.4, nice plugin!
